# Site settings
author: John Million
title: Fantasy Football App
header-img: img/home-bg.png
email: jpmillion@comcast.net
copyright_name: John Million
description: > # this means to ignore newlines until "baseurl:"
  Fantasy Football
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jpmillion

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
